In [4]:
import pandas as pd, numpy as np, re
from sklearn.preprocessing import MultiLabelBinarizer


def parse_data(file_name):
    features = list()
    labels = list()
    with open(file_name, 'rt') as f:
        f.readline()
        for l in f:
            if bool(re.search("^[0-9]", l)):
                g = re.search("^(([0-9]{1,2},?)+)\s(.*)$", l)
                labels.append([int(i) for i in g.group(1).split(",")])
                features.append(eval("{" + re.sub("\s", ",", g.group(3)) + "}"))
            else:
                l = l.strip()
                labels.append([])
                features.append(eval("{" + re.sub("\s", ",", l) + "}"))
    features = pd.DataFrame.from_dict(features).fillna(0).iloc[:,:].values
    mlb = MultiLabelBinarizer()
    y = mlb.fit_transform(labels)
    return features, labels

X, y = parse_data("loc_1.txt")

In [16]:
import dill
with open("model_0_loc1.dill", 'rb') as model_file:
    model = dill.load(model_file)

/home/aziza/.local/lib/python3.6/site-packages/sklearn/utils/deprecation.py:144: FutureWarning: The sklearn.linear_model.logistic module is  deprecated in version 0.22 and will be removed in version 0.24. The corresponding classes / functions should instead be imported from sklearn.linear_model. Anything that cannot be imported from sklearn.linear_model is now part of the private API.
  warnings.warn(message, FutureWarning)


In [18]:
idx = np.random.randint(len(X), size=10)
for i in idx:
  action = model.predict(X[idx, :]).astype("uint8")
  print(action)

[0 0 1 0 0 0 0 1 1 1]
[0 0 1 1 1 1 1 0 1 1]
[1 0 1 1 0 1 0 0 1 1]
[1 1 1 1 0 0 0 0 1 0]
[0 1 0 0 0 0 0 1 0 1]
[1 0 0 0 0 0 1 0 1 1]
[0 0 1 1 0 0 0 1 1 1]
[1 1 0 0 1 0 1 1 1 1]
[0 0 0 0 1 1 0 0 1 0]
[1 1 0 1 0 1 1 1 0 0]


In [22]:
print([model.rewards])

AttributeError: 'BootstrappedUCB' object has no attribute 'rewards'

In [23]:
model